// Generated by dts-bundle v0.3.0
// Dependencies for this module:
//   typings/bluebird/bluebird.d.ts

declare module 'use-dts-bundle' {
    import P = require('bluebird');
    export { foo, bar } from '__use-dts-bundle/myutil';
    export function baz(): P<void>;
}

declare module '__use-dts-bundle/myutil' {
    import P = require('bluebird');
    export function foo(): P<void>;
    export function bar(): P<void>;
}

